columns:
  current:
    rename: Current
    unit: amp
  cycle_number:
    rename: Cycle Number
  method:
    rename: Method
  state:
    rename: State
  step_index:
    rename: Step Index
  substep_index:
    rename: Substep Index
  test_time:
    rename: Test Time
    unit: second
  voltage:
    rename: Potential
    unit: volt
metadata:
  Start Time: 123
  Timezone: America/Chicago
